Tisseo\DatawarehouseBundle\Entity\CalendarElement:
    type: entity
    table: calendar_element
    indexes:
        calendar_element_calendar_id_idx:
            columns:
                - calendar_id
        IDX_233725FE484DE9F9:
            columns:
                - included_calendar_id
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: "\n"
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        startDate:
            type: date
            nullable: true
            comment: ''
            column: start_date
        endDate:
            type: date
            nullable: true
            comment: ''
            column: end_date
        positive:
            type: calendar_operator
            nullable: false
            length: 1
            fixed: false
            requireSQLConversion: true
            comment: 'agencement des calendar_element d''un meme calendrier : ajout, soustraction, intersection avec les precedents'
        interval:
            type: integer
            nullable: true
            unsigned: false
            comment: 'intervalle de repetition en cas de calendrier recurrent (lundi)'
    manyToOne:
        calendar:
            targetEntity: Calendar
            mappedBy: null
            inversedBy: calendarElements
            joinColumns:
                calendar_id:
                    referencedColumnName: id
        includedCalendar:
            targetEntity: Calendar
            mappedBy: null
            inversedBy: null
            joinColumns:
                included_calendar_id:
                    referencedColumnName: id
    lifecycleCallbacks: {  }
