Tisseo\DatawarehouseBundle\Entity\CalendarLink:
    type: entity
    table: calendar_link
    indexes:
        calendar_link_day_calendar_id_idx:
            columns:
                - day_calendar_id
        calendar_link_period_calendar_id_idx:
            columns:
                - period_calendar_id
        calendar_link_trip_id_idx:
            columns:
                - trip_id
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: SEQUENCE
    manyToOne:
        dayCalendar:
            targetEntity: Calendar
            mappedBy: null
            inversedBy: calendarLinksDay
            joinColumns:
                day_calendar_id:
                    referencedColumnName: id
        periodCalendar:
            targetEntity: Calendar
            cascade: ['persist', 'remove']
            mappedBy: null
            inversedBy: calendarLinksPeriod
            joinColumns:
                period_calendar_id:
                    referencedColumnName: id
        trip:
            targetEntity: Trip
            mappedBy: null
            inversedBy: calendarLinks
            joinColumns:
                trip_id:
                    referencedColumnName: id
    lifecycleCallbacks: {  }
