Tisseo\DatawarehouseBundle\Entity\CalendarElement:
    type: entity
    table: calendar_element
    indexes:
        calendar_element_calendar_id_idx:
            columns:
                - calendar_id
        IDX_233725FE484DE9F9:
            columns:
                - included_calendar_id
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: "\n"
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        startDate:
            type: date
            nullable: true
            column: start_date
        endDate:
            type: date
            nullable: true
            column: end_date
        positive:
            type: string
            nullable: false
            length: 1
            fixed: false
        interval:
            type: integer
            nullable: true
            unsigned: false
    manyToOne:
        calendar:
            targetEntity: Calendar
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                calendar_id:
                    referencedColumnName: id
            orphanRemoval: false
        includedCalendar:
            targetEntity: Calendar
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                included_calendar_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
