Tisseo\DatawarehouseBundle\Entity\Calendar:
    type: entity
    table: calendar
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        name:
            type: string
            nullable: false
            length: 50
            fixed: false
            comment: ''
        calendarType:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            column: calendar_type
    lifecycleCallbacks: {  }
