Tisseo\DatawarehouseBundle\Entity\ChangeCause:
    type: entity
    table: change_cause
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        description:
            type: string
            nullable: true
            length: 255
            fixed: false
            comment: ''
    oneToMany:
        changeCauseLinks:
            targetEntity: ChangeCauseLink
            cascade: {  }
            mappedBy: changeCause
            inversedBy: null
            orphanRemoval: false
            fetch: 'EXTRA_LAZY'
    lifecycleCallbacks: {  }
