Tisseo\DatawarehouseBundle\Entity\ExportPerso:
    type: entity
    table: export_perso
    id:
        tableName:
            type: string
            nullable: false
            length: 30
            fixed: false
            comment: ''
            id: true
            column: table_name
            generator:
                strategy: SEQUENCE
    lifecycleCallbacks: {  }
