Tisseo\DatawarehouseBundle\Entity\LineVersionNotExported:
    type: entity
    table: line_version_not_exported
    indexes:
        IDX_17585275A574F401:
            columns:
                - export_destination_id
        IDX_17585275F50734EE:
            columns:
                - line_version_id
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: SEQUENCE
    manyToOne:
        exportDestination:
            targetEntity: ExportDestination
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                export_destination_id:
                    referencedColumnName: id
            orphanRemoval: false
        lineVersion:
            targetEntity: LineVersion
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                line_version_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
