Tisseo\DatawarehouseBundle\Entity\Log:
    type: entity
    table: log
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        datetime:
            type: datetime
            nullable: false
        table:
            type: string
            nullable: false
            length: 30
            fixed: false
        action:
            type: string
            nullable: false
            length: 20
            fixed: false
        previousData:
            type: text
            nullable: true
            length: null
            fixed: false
            column: previous_data
        insertedData:
            type: text
            nullable: true
            length: null
            fixed: false
            column: inserted_data
        user:
            type: string
            nullable: false
            length: 30
            fixed: false
    lifecycleCallbacks: {  }
