Tisseo\DatawarehouseBundle\Entity\RouteSection:
    type: entity
    table: route_section
    indexes:
        IDX_D5202777ACCD57D4:
            columns:
                - end_stop_id
        IDX_D5202777C9C75AEE:
            columns:
                - start_stop_id
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        startDate:
            type: date
            nullable: false
            comment: 'Date de la creation de ce troncon. Un nouveau troncon est cree si arret debut ou arret fin ou geom est nouvelle.'
            column: start_date
        endDate:
            type: date
            nullable: true
            comment: 'Date de fin d''utilisation du troncon. Lorsqu''un nouveau troncon (meme debut, meme fin mais geom differente) est cree, le precedentest cloture.'
            column: end_date
        theGeom:
            type: geometry
            nullable: false
            comment: 'Geometrie de Tigre.'
            requireSQLConversion: true
            column: the_geom
    manyToOne:
        endStop:
            targetEntity: Stop
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                end_stop_id:
                    referencedColumnName: id
            orphanRemoval: false
        startStop:
            targetEntity: Stop
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                start_stop_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
