Tisseo\DatawarehouseBundle\Entity\Route:
    type: entity
    table: route
    indexes:
        route_line_version_id_idx:
            columns:
                - line_version_id
        IDX_2C42079F8697D13:
            columns:
                - comment_id
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        way:
            type: string
            nullable: false
            length: 10
            fixed: false
            comment: 'Aller ou retour.'
        name:
            type: string
            nullable: false
            length: 100
            fixed: false
            comment: 'Nom du parcours type (Hastus ou Tigre).'
        direction:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: 'Titre de la direction, a terme, viendra de l''application girouette.'
    manyToOne:
        comment:
            targetEntity: Comment
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                comment_id:
                    referencedColumnName: id
            orphanRemoval: false
        lineVersion:
            targetEntity: LineVersion
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                line_version_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
