Tisseo\DatawarehouseBundle\Entity\StopHistory:
    type: entity
    table: stop_history
    indexes:
        IDX_8065666D3902063D:
            columns:
                - stop_id
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        startDate:
            type: date
            nullable: false
            column: start_date
        endDate:
            type: date
            nullable: true
            column: end_date
        shortName:
            type: string
            nullable: false
            length: 50
            fixed: false
            column: short_name
        longName:
            type: string
            nullable: true
            length: 255
            fixed: false
            column: long_name
        theGeom:
            type: geometry
            nullable: false
            requireSQLConversion: true
            column: the_geom
        accessibility:
            type: boolean
            nullable: true
    manyToOne:
        stop:
            targetEntity: Stop
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                stop_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
