Tisseo\DatawarehouseBundle\Entity\Transfer:
    type: entity
    table: transfer
    indexes:
        IDX_4034A3C0ACCD57D4:
            columns:
                - end_stop_id
        IDX_4034A3C0C9C75AEE:
            columns:
                - start_stop_id
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        duration:
            type: integer
            nullable: false
            unsigned: false
            comment: 'Temps de transfert en secondes.'
        distance:
            type: integer
            nullable: true
            unsigned: false
            comment: 'Distance en metres de la correspondance.'
        theGeom:
            type: geometry
            nullable: true
            comment: 'Trace de la correspondance. Inutilise pour le moment.'
            requireSQLConversion: true
            column: the_geom
        accessibility:
            type: boolean
            nullable: true
            comment: 'Accessibilite de la correspondance. Inutilise pour le moment.'
        description:
            type: text
            nullable: true
            length: null
            fixed: false
            comment: ''
    manyToOne:
        endStop:
            targetEntity: Stop
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                end_stop_id:
                    referencedColumnName: id
            orphanRemoval: false
        startStop:
            targetEntity: Stop
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                start_stop_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
