Tisseo\DatawarehouseBundle\Entity\Trip:
    type: entity
    table: trip
    indexes:
        trip_route_id_idx:
            columns:
                - route_id
        IDX_7656F53BF8697D13:
            columns:
                - comment_id
        IDX_7656F53BFE610542:
            columns:
                - trip_calendar_id
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        name:
            type: string
            nullable: false
            length: 20
            fixed: false
    manyToOne:
        comment:
            targetEntity: Comment
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                comment_id:
                    referencedColumnName: id
            orphanRemoval: false
        route:
            targetEntity: Route
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                route_id:
                    referencedColumnName: id
            orphanRemoval: false
        tripCalendar:
            targetEntity: TripCalendar
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                trip_calendar_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
