Tisseo\DatawarehouseBundle\Entity\Trip:
    type: entity
    table: trip
    indexes:
        trip_route_id_idx:
            columns:
                - route_id
        IDX_7656F53BF8697D13:
            columns:
                - comment_id
        IDX_7656F53BFE610542:
            columns:
                - trip_calendar_id
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        name:
            type: string
            nullable: false
            length: 20
            fixed: false
            comment: 'Nom de l''objet. Si vient d''Hastus, identiques a la datasource.'
    oneToMany:
        calendarLinks:
            targetEntity: CalendarLink
            mappedBy: trip
            inversedBy: null
            orphanRemoval: true
            fetch: "EXTRA_LAZY"
        stopTimes:
            targetEntity: StopTime
            mappedBy: trip
            inversedBy: null
            orphanRemoval: true
            fetch: "EXTRA_LAZY"
        tripDatasources:
            targetEntity: TripDatasource
            mappedBy: trip
            inversedBy: null
            orphanRemoval: true
            fetch: "EXTRA_LAZY"
    manyToOne:
        comment:
            targetEntity: Comment
            mappedBy: null
            inversedBy: null
            joinColumns:
                comment_id:
                    referencedColumnName: id
        route:
            targetEntity: Route
            mappedBy: null
            inversedBy: trips
            joinColumns:
                route_id:
                    referencedColumnName: id
        tripCalendar:
            targetEntity: TripCalendar
            mappedBy: null
            inversedBy: trips
            joinColumns:
                trip_calendar_id:
                    referencedColumnName: id
    lifecycleCallbacks: {  }
