parameters:
    paon.permissions:
        BUSINESS_LIST_LINE:
            label: Afficher la liste des lignes
            description: Afficher la liste des lignes de transport
        BUSINESS_MANAGE_LINE:
            label: Administrer les lignes
            description: Administrer les lignes de transport
        BUSINESS_LIST_LINE_VERSION:
            label: Afficher la liste des offres
            description: Afficher la liste des offres
        BUSINESS_MANAGE_LINE_VERSION:
            label: Administrer les offres
            description: Administrer les offres
        BUSINESS_MANAGE_GRID_CALENDAR:
            label: Administrer les grilles horaires
            description: Administrer les grilles horaires et les calendriers de services
        BUSINESS_MANAGE_EXCEPTION:
            label: Administrer les exceptions
            description: Administrer les exceptions sur les services
        BUSINESS_MANAGE_DATA_EXCHANGE:
            label: Administrer certains imports et exports de données (limité)
            description: >
              Droit de lancer des imports ou exports de données (certains imports/exports peuvent ne pas
              être disponibles)
        BUSINESS_MANAGE_DATA_EXCHANGE_ROOT:
            label: Administrer l'ensemble de imports et exports de données
            description: Droit de lancer l'ensemble des imports ou exports de données
        BUSINESS_LIST_SCHEMA:
            label: Accéder à la gestion des schémas
            description: Afficher la liste des schématiques par ligne
        BUSINESS_MANAGE_NEW_SCHEMA:
            label: Accéder au formulaire d'ajout d'un nouveau schéma
            description: Déposer un fichier / Ajouter un commentaire
        BUSINESS_MANAGE_ASK_SCHEMA:
            label: Accéder au formulaire de demande d'un schéma
            description: Formulaire d'envoi de mail pour nouveau schéma
        BUSINESS_MANAGE_DEPRECATE_SCHEMA:
            label: Accéder au formulaire de déclaration de schéma obsolète
            description: Déclarer un schéma obsolète
        BUSINESS_MANAGE_DELETE_SCHEMA:
            label: Accéder au formulaire de suppression de schema
            description: Supprimer un schéma
        BUSINESS_LIST_GROUP_GIS:
            label: Accéder à la liste des voussures
            description:
        BUSINESS_MANAGE_GROUP_GIS:
            label: Administrer les voussures
            description:
