tisseo_tid_homepage:
    pattern:  /
    defaults: { _controller: TisseoTidBundle:Default:index }

#Line administration
tisseo_tid_line_list:
    pattern: /lines/list
    defaults: { _controller: TisseoTidBundle:Line:list }
tisseo_tid_line_edit:
    pattern: /lines/edit/{lineId}
    defaults: { _controller: TisseoTidBundle:Line:edit, lineId: null }

#LineVersion administration
tisseo_tid_line_version_list:
    pattern: /offers/list
    defaults: { _controller: TisseoTidBundle:LineVersion:list }
tisseo_tid_line_version_history:
    pattern: /offers/history
    defaults: { _controller: TisseoTidBundle:LineVersion:history }
tisseo_tid_line_version_edit:
    pattern: /offers/edit/{lineVersionId}
    defaults: { _controller: TisseoTidBundle:LineVersion:edit, lineVersionId: null }
tisseo_tid_line_version_consult:
    pattern: /offers/consult/{lineVersionId}
    defaults: { _controller: TisseoTidBundle:LineVersion:consult }
    options:
        expose: true
tisseo_tid_line_version_close:
    pattern: /offers/close/{lineVersionId}
    defaults: { _controller: TisseoTidBundle:LineVersion:close }
    requirements:
        lineVersionId: \d+
tisseo_tid_line_version_purge:
    pattern: /offers/purge/{lineVersionId}
    defaults: { _controller: TisseoTidBundle:LineVersion:purge }
    requirements:
        lineVersionId: \d+
tisseo_tid_printing_create:
    pattern: /offers/add/printings/{lineVersionId}
    defaults: { _controller: TisseoTidBundle:Printing:create }
    requirements:
        lineVersionId: \d+
tisseo_tid_select_line_version_by_line:
    pattern: /offers/select_by_line
    defaults: { _controller: TisseoTidBundle:LineVersion:selectByLine }
    options:
        expose: true

#Calendar administration
tisseo_tid_calendar_list:
    pattern: /calendars/list
    defaults: { _controller: TisseoTidBundle:Calendar:list }
tisseo_tid_calendar_edit:
    pattern: /calendars/edit/{lineVersionId}
    defaults: { _controller: TisseoTidBundle:Calendar:edit }
    requirements:
        lineVersionId: \d+
    options:
        expose: true
tisseo_tid_calendar_form:
    pattern: /offers/add/calendar/{lineVersionId}
    defaults: { _controller: TisseoTidBundle:Calendar:renderForm }
    requirements:
        lineVersionId: \d+
    options:
        expose: true
tisseo_tid_calendar_create:
    pattern: /offers/create/calendar/{lineVersionId}
    defaults: { _controller: TisseoTidBundle:Calendar:create }
    requirements:
        lineVersionId: \d+
    options:
        expose: true

#Exception administration
tisseo_tid_exception_list:
    pattern: /exceptions/list
    defaults: { _controller: TisseoTidBundle:Exception:list }
tisseo_tid_exception_edit:
    pattern: /exceptions/edit/{lineVersionId}
    defaults: { _controller: TisseoTidBundle:Exception:edit, lineVersionId: null }
    options:
        expose: true
tisseo_tid_exception_comment:
    pattern: /exceptions/create/comment
    defaults: { _controller: TisseoTidBundle:Exception:comment }
    options:
        expose: true

#Imports administration
tisseo_tid_data_exchange_import:
    pattern: /data-exchange
    defaults: { _controller: TisseoTidBundle:DataExchange:import }
tisseo_tid_data_exchange_edit:
    pattern: /data-exchange/{jobName}
    defaults: { _controller: TisseoTidBundle:DataExchange:edit, jobName: null }

#Export administration
tisseo_tid_export_timetable:
    pattern: /exports/timetable
    defaults: { _controller: TisseoTidBundle:Export:timetable }
