tisseo_paon_homepage:
    pattern:  /
    defaults: { _controller: TisseoPaonBundle:Default:index }

# Line routes
tisseo_paon_line_list:
    pattern: /lines/list
    defaults: { _controller: TisseoPaonBundle:Line:list }
tisseo_paon_line_edit:
    pattern: /lines/edit/{lineId}
    defaults: { _controller: TisseoPaonBundle:Line:edit, lineId: null }

# LineVersion routes
tisseo_paon_line_version_list:
    pattern: /offers/list
    defaults: { _controller: TisseoPaonBundle:LineVersion:list }
tisseo_paon_line_version_history:
    pattern: /offers/history
    defaults: { _controller: TisseoPaonBundle:LineVersion:history }
tisseo_paon_line_version_edit:
    pattern: /offers/edit/{lineVersionId}
    defaults: { _controller: TisseoPaonBundle:LineVersion:edit }
    requirements:
        lineVersionId: \d+
tisseo_paon_line_version_create:
    pattern: /offers/create/{lineId}
    defaults: { _controller: TisseoPaonBundle:LineVersion:create, lineId: null }
    options:
        expose: true
tisseo_paon_line_version_show:
    pattern: /offers/show/{lineVersionId}
    defaults: { _controller: TisseoPaonBundle:LineVersion:show }
    requirements:
        lineVersionId: \d+
    options:
        expose: true
tisseo_paon_line_version_close:
    pattern: /offers/close/{lineVersionId}
    defaults: { _controller: TisseoPaonBundle:LineVersion:close }
    requirements:
        lineVersionId: \d+
tisseo_paon_line_version_clean:
    pattern: /offers/clean/{lineVersionId}
    defaults: { _controller: TisseoPaonBundle:LineVersion:clean }
    requirements:
        lineVersionId: \d+
tisseo_paon_line_version_delete:
    pattern: /offers/delete/{lineVersionId}
    defaults: { _controller: TisseoPaonBundle:LineVersion:delete }
    requirements:
        lineVersionId: \d+

# Printing routes
tisseo_paon_printing_create:
    pattern: /offers/add/printings/{lineVersionId}
    defaults: { _controller: TisseoPaonBundle:Printing:create }
    requirements:
        lineVersionId: \d+

# GridCalendar/GridMaskType routes
tisseo_paon_calendar_edit:
    pattern: /calendars/edit/{lineVersionId}
    defaults: { _controller: TisseoPaonBundle:Calendar:edit }
    requirements:
        lineVersionId: \d+
    options:
        expose: true
tisseo_paon_calendar_form:
    pattern: /offers/add/calendar/{lineVersionId}
    defaults: { _controller: TisseoPaonBundle:Calendar:renderForm }
    requirements:
        lineVersionId: \d+
    options:
        expose: true
tisseo_paon_calendar_create:
    pattern: /offers/create/calendar/{lineVersionId}
    defaults: { _controller: TisseoPaonBundle:Calendar:create }
    requirements:
        lineVersionId: \d+
    options:
        expose: true

# Exception/Comment administration
tisseo_paon_exception_edit:
    pattern: /exceptions/edit/{lineVersionId}
    defaults: { _controller: TisseoPaonBundle:Exception:edit, lineVersionId: null }
    options:
        expose: true
tisseo_paon_exception_comment:
    pattern: /exceptions/create/comment
    defaults: { _controller: TisseoPaonBundle:Exception:comment }
    options:
        expose: true

# Imports administration
tisseo_paon_data_exchange_show:
    pattern: /data-exchange/show
    defaults: { _controller: TisseoPaonBundle:DataExchange:show }
tisseo_paon_data_exchange_jobs:
    pattern: /data-exchange/jobs
    defaults: { _controller: TisseoPaonBundle:DataExchange:jobs }
    options:
        expose: true
tisseo_paon_data_exchange_launch:
    pattern: /data-exchange/launch/{jobName}
    defaults: { _controller: TisseoPaonBundle:DataExchange:launch, jobName: null }

# Line schema administration
tisseo_paon_line_schema_list:
    pattern: /line-schema/list
    defaults: { _controller: TisseoPaonBundle:LineSchema:list }
tisseo_paon_schema_list:
    pattern: /line-schema/{lineId}/schema/list
    defaults: { _controller: TisseoPaonBundle:LineSchema:listSchema }
    requirements:
        lineId: \d+
tisseo_paon_schema_choice_list:
    pattern: /line-schema/{lineId}/schema/choice/list/{schematicId}
    defaults: { _controller: TisseoPaonBundle:LineSchema:choiceListSchema, schematicId: null }
    requirements:
        lineId: \d+
    options:
        expose: true
tisseo_paon_schema_edit:
    pattern: /line-schema/{lineId}/schema/edit
    defaults: { _controller: TisseoPaonBundle:LineSchema:editSchema }
    requirements:
        lineId: \d+
    options:
        expose: true
tisseo_paon_schema_ask:
    pattern: /line-schema/{lineId}/schema/ask
    defaults: { _controller: TisseoPaonBundle:LineSchema:askSchema }
    requirements:
        lineId: \d+
    options:
        expose: true
tisseo_paon_schema_deprecated:
    pattern: /line-schema/{lineId}/schema/deprecated
    defaults: { _controller: TisseoPaonBundle:LineSchema:deprecatedSchema }
    requirements:
        lineId: \d+
    options:
        expose: true

# Line Group Gis
tisseo_paon_line_group_gis_list:
    pattern: /line-schema/line-group/list
    defaults: { _controller: TisseoPaonBundle:LineGroupGis:list }
tisseo_paon_line_group_gis_create:
    pattern: /line-schema/line-group/edit/create
    defaults: { _controller: TisseoPaonBundle:LineGroupGis:create }
tisseo_paon_line_group_gis_edit:
    pattern: /line-schema/line-group/edit/{lineGroupGisId}
    defaults: { _controller: TisseoPaonBundle:LineGroupGis:edit }
    requirements:
        lineGroupGisId: \d+
tisseo_paon_line_group_gis_delete:
    pattern: /line-schema/line-group/delete/{lineGroupGisId}
    defaults: { _controller: TisseoPaonBundle:LineGroupGis:delete }
    requirements:
        lineGroupGisId: \d+
