tisseo_datawarehouse_homepage:
    pattern:  /
    defaults: { _controller: TisseoDatawarehouseBundle:Default:index }

#Line administration
tisseo_datawarehouse_line_list:
    pattern: /lines/list
    defaults: { _controller: TisseoDatawarehouseBundle:Line:list}
tisseo_datawarehouse_line_edit:
    pattern: /lines/edit/{lineId}
    defaults: { _controller: TisseoDatawarehouseBundle:Line:edit, lineId: null }

#LineVersion administration
tisseo_datawarehouse_line_version_list:
    pattern: /offers/list
    defaults: { _controller: TisseoDatawarehouseBundle:LineVersion:list}
tisseo_datawarehouse_line_version_edit:
    pattern: /offers/edit/{lineVersionId}
    defaults: { _controller: TisseoDatawarehouseBundle:LineVersion:edit, lineVersionId: null }
tisseo_datawarehouse_line_version_consult:
    pattern: /offers/consult/{lineVersionId}
    defaults: { _controller: TisseoDatawarehouseBundle:LineVersion:consult }
tisseo_datawarehouse_select_line_version_by_line:
    pattern: /offers/select_by_line
    defaults: { _controller: TisseoDatawarehouseBundle:LineVersion:selectByLine }
    options:
        expose: true

#Calendar administration
tisseo_datawarehouse_calendar_list:
    pattern: /calendars/list
    defaults: { _controller: TisseoDatawarehouseBundle:Calendar:list}
tisseo_datawarehouse_calendar_edit:
    pattern: /calendars/edit/{calendarId}
    defaults: { _controller: TisseoDatawarehouseBundle:Calendar:edit, calendarId: null }

#ExceptionType administration
tisseo_datawarehouse_exception_type_list:
    pattern: /exceptions/list
    defaults: { _controller: TisseoDatawarehouseBundle:ExceptionType:list}
tisseo_datawarehouse_exception_type_edit:
    pattern: /exceptions/edit/{exceptionTypeId}
    defaults: { _controller: TisseoDatawarehouseBundle:ExceptionType:edit, exceptionTypeId: null }

#Imports administration
tisseo_datawarehouse_import_fichor:
    pattern: /imports/fichor
    defaults: { _controller: TisseoDatawarehouseBundle:Import:fichor}

#Export administration
tisseo_datawarehouse_export_timetable:
    pattern: /exports/timetable
    defaults: { _controller: TisseoDatawarehouseBundle:Export:timetable}
