tisseo_datawarehouse_homepage:
    pattern:  /
    defaults: { _controller: TisseoDatawarehouseBundle:Default:index }

#Line administration
tisseo_datawarehouse_line_list:
    pattern: /lines/list
    defaults: { _controller: TisseoDatawarehouseBundle:Line:list}
tisseo_datawarehouse_line_edit:
    pattern: /lines/edit/{lineId}
    defaults: { _controller: TisseoDatawarehouseBundle:Line:edit, lineId: null }
