tisseo_tid_homepage:
    pattern:  /
    defaults: { _controller: TisseoTidBundle:Default:index }

# Line routes
tisseo_tid_line_list:
    pattern: /lines/list
    defaults: { _controller: TisseoTidBundle:Line:list }
tisseo_tid_line_edit:
    pattern: /lines/edit/{lineId}
    defaults: { _controller: TisseoTidBundle:Line:edit, lineId: null }

# LineVersion routes
tisseo_tid_line_version_list:
    pattern: /offers/list
    defaults: { _controller: TisseoTidBundle:LineVersion:list }
tisseo_tid_line_version_history:
    pattern: /offers/history
    defaults: { _controller: TisseoTidBundle:LineVersion:history }
tisseo_tid_line_version_edit:
    pattern: /offers/edit/{lineVersionId}
    defaults: { _controller: TisseoTidBundle:LineVersion:edit, lineVersionId: null }
tisseo_tid_line_version_show:
    pattern: /offers/show/{lineVersionId}
    defaults: { _controller: TisseoTidBundle:LineVersion:show }
    options:
        expose: true
tisseo_tid_line_version_close:
    pattern: /offers/close/{lineVersionId}
    defaults: { _controller: TisseoTidBundle:LineVersion:close }
    requirements:
        lineVersionId: \d+
tisseo_tid_line_version_clean:
    pattern: /offers/clean/{lineVersionId}
    defaults: { _controller: TisseoTidBundle:LineVersion:clean }
    requirements:
        lineVersionId: \d+
tisseo_tid_select_line_version_by_line:
    pattern: /offers/select_by_line
    defaults: { _controller: TisseoTidBundle:LineVersion:selectByLine }
    options:
        expose: true

# Printing routes
tisseo_tid_printing_create:
    pattern: /offers/add/printings/{lineVersionId}
    defaults: { _controller: TisseoTidBundle:Printing:create }
    requirements:
        lineVersionId: \d+

# GridCalendar/GridMaskType routes
tisseo_tid_calendar_edit:
    pattern: /calendars/edit/{lineVersionId}
    defaults: { _controller: TisseoTidBundle:Calendar:edit }
    requirements:
        lineVersionId: \d+
    options:
        expose: true
tisseo_tid_calendar_form:
    pattern: /offers/add/calendar/{lineVersionId}
    defaults: { _controller: TisseoTidBundle:Calendar:renderForm }
    requirements:
        lineVersionId: \d+
    options:
        expose: true
tisseo_tid_calendar_create:
    pattern: /offers/create/calendar/{lineVersionId}
    defaults: { _controller: TisseoTidBundle:Calendar:create }
    requirements:
        lineVersionId: \d+
    options:
        expose: true

# Exception/Comment administration
tisseo_tid_exception_edit:
    pattern: /exceptions/edit/{lineVersionId}
    defaults: { _controller: TisseoTidBundle:Exception:edit, lineVersionId: null }
    options:
        expose: true
tisseo_tid_exception_comment:
    pattern: /exceptions/create/comment
    defaults: { _controller: TisseoTidBundle:Exception:comment }
    options:
        expose: true

# Imports administration
tisseo_tid_data_exchange_show:
    pattern: /data-exchange/show
    defaults: { _controller: TisseoTidBundle:DataExchange:show }
tisseo_tid_data_exchange_launch:
    pattern: /data-exchange/launch/{jobName}
    defaults: { _controller: TisseoTidBundle:DataExchange:launch, jobName: null }

# Line schema administration
tisseo_tid_line_schema_list:
    pattern: /line-schema/list
    defaults: { _controller: TisseoTidBundle:LineSchema:list }
tisseo_tid_schema_list:
    pattern: /line-schema/{lineId}/schema/list
    defaults: { _controller: TisseoTidBundle:LineSchema:listSchema }
    requirements:
        lineId: \d+
tisseo_tid_schema_choice_list:
    pattern: /line-schema/{lineId}/schema/choice/list/{schematicId}
    defaults: { _controller: TisseoTidBundle:LineSchema:choiceListSchema, schematicId: null }
    requirements:
        lineId: \d+
    options:
        expose: true
tisseo_tid_schema_edit:
    pattern: /line-schema/{lineId}/schema/edit
    defaults: { _controller: TisseoTidBundle:LineSchema:editSchema }
    requirements:
        lineId: \d+
    options:
        expose: true
tisseo_tid_schema_ask:
    pattern: /line-schema/{lineId}/schema/ask
    defaults: { _controller: TisseoTidBundle:LineSchema:askSchema }
    requirements:
        lineId: \d+
    options:
        expose: true

# Line Group Gis
tisseo_tid_line_group_gis_list:
    pattern: /line-schema/line-group/list
    defaults: { _controller: TisseoTidBundle:LineGroupGis:list }