parameters:
    tisseo_tid.perimeter.class: Tisseo\TidBundle\Services\PerimeterManager
    tisseo_tid.user.class: Tisseo\TidBundle\Services\UserManager
    tisseo_tid.data_exchange_manager.class: Tisseo\TidBundle\Services\DataExchangeManager

services:
    tisseo_tid.perimeter_manager:
        class: %tisseo_tid.perimeter.class%
        arguments: ['@doctrine.orm.default_entity_manager']
    tisseo_tid.user_manager:
        class: %tisseo_tid.user.class%
        arguments: ['@doctrine.orm.default_entity_manager', '@translator', '@service_container']
    tisseo_tid.data_exchange_manager:
        class: %tisseo_tid.data_exchange_manager.class%
        arguments: ['%tisseo_tid.jenkins_server%', '%tisseo_tid.jenkins_user%', '%tisseo_tid.master_job_prefix%', '%tisseo_tid.atomic_job_prefix%']

    form.type.datepicker_tid:
        class: Tisseo\TidBundle\Form\Type\DatepickerType
        tags:
            - { name: form.type, alias: datepicker_tid }

    form.type.tid_line_group_gis:
        class: Tisseo\TidBundle\Form\Type\LineGroupGisType
        tags:
            - { name: form.type, alias: tid_line_group_gis }

    tisseo_tid.ajax_form_listener:
        class: CanalTP\SamCoreBundle\EventListener\AjaxFormListener
        tags:
            - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse }
