services:
    tisseo_paon.data_exchange_manager:
        class: 'Tisseo\PaonBundle\Services\DataExchangeManager'
        arguments:
            - '%tisseo_paon.jenkins_server%'
            - '%tisseo_paon.jenkins_users%'
            - '%tisseo_paon.master_job_prefix%'
            - '%tisseo_paon.atomic_job_prefix%'

    form.type.paon_line_group_gis:
        class: 'Tisseo\PaonBundle\Form\Type\LineGroupGisType'
        tags:
            - { name: form.type, alias: paon_line_group_gis }

    tisseo_paon.ajax_form_listener:
        class: 'CanalTP\SamCoreBundle\EventListener\AjaxFormListener'
        tags:
            - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse }
