Tisseo\EndivBundle\Entity\Line:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: number
            errorPath: number
            message: error.line_exists
    properties:
        number:
            - NotBlank: ~
            - Length:
                max: 20
Tisseo\EndivBundle\Entity\LineDatasource:
    properties:
        code:
            - NotBlank: ~
Tisseo\EndivBundle\Entity\Printing:
    properties:
        quantity:
            - NotBlank: ~
            - GreaterThan:
                value: 1
        date:
            - DateTime: ~
Tisseo\EndivBundle\Entity\GridCalendar:
    properties:
        name:
            - NotBlank: ~
Tisseo\EndivBundle\Entity\LineVersion:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            groups: [registration]
            fields: [line, version]
            errorPath: version
            message: error.line_version.already_exists
    properties:
        name:
            - NotBlank: ~
            - Length:
                min: 4
        startDate:
            - DateTime: ~
        plannedEndDate:
            - DateTime: ~
            - Tisseo\PaonBundle\Validator\Constraints\GreaterThanField:
                groups: [registration]
                field: startDate
        endDate:
            - DateTime: ~
            - Tisseo\PaonBundle\Validator\Constraints\GreaterThanField:
                groups: [close]
                field: startDate
Tisseo\EndivBundle\Entity\Comment:
    properties:
        label:
            - Length:
                min: 1
                max: 4
                minMessage: error.comment.label_length
                maxMessage: error.comment.label_length
            - Type:
                type: alpha
                message: error.comment.label_type
            - Type:
                type: string
