Tisseo\EndivBundle\Entity\Line:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: number
            errorPath: number
            message: error.line_exists
    properties:
        number:
            - NotBlank: ~
            - Length:
                max: 20
Tisseo\EndivBundle\Entity\LineDatasource:
    properties:
        code:
            - NotBlank: ~
Tisseo\EndivBundle\Entity\Printing:
    properties:
        quantity:
            - NotBlank: ~
            - GreaterThan:
                value: 1
        date:
            - DateTime: ~
Tisseo\EndivBundle\Entity\GridCalendar:
    properties:
        name:
            - NotBlank: ~
Tisseo\EndivBundle\Entity\LineVersion:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            groups: [registration]
            fields: [name, version]
            errorPath: name
            message: error.line_version_exists
    properties:
        name:
            - NotBlank: ~
            - Length:
                min: 4
        startDate:
            - DateTime: ~
        plannedEndDate:
            - DateTime: ~
            - Tisseo\TidBundle\Validator\Constraints\GreaterThanField:
                field: startDate
        endDate:
            - DateTime: ~
            - Tisseo\TidBundle\Validator\Constraints\GreaterThanField:
                field: startDate
