Tisseo\DatawarehouseBundle\Entity\Line:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: number
    properties:
        number:
            - NotBlank: ~
            - Length:
                max: 20
